name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  injectable: ^2.1.0
  get_it: ^7.2.0
  keyboard_dismisser: ^3.0.0
  logger:
    git:
      url: https://github.com/phonex34/logger.git
  pretty_dio_logger: ^1.3.1
  auto_route: ^6.0.5
  awesome_snackbar_content: ^0.1.2
  dio: ^5.0.1
  equatable: ^2.0.5
  {{#isBloc}}
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  {{/isBloc}}
  {{#isGetX}}
  get: ^4.6.5
  {{/isGetX}}

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.4 
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  build_runner:
  {{#isBloc}}
  bloc_test: ^9.1.1
  {{/isBloc}}
  auto_route_generator: ^6.0.2

flutter:
  uses-material-design: true
  generate: true
